### ISSUE TITLE
Please can you help me

### ISSUE THREAD

**Issue by danieljohnmorris** [XeroAPI/xero-ruby-oauth2-starter#4]
Hi, I have tried twice to speak to Xero API support, and they refer me to opening a github issue instead.

We are unable to set up either xero-ruby-oauth2-app or xero-ruby-oauth2-starter.

Have followed the readme instructions, created the .env, but when I "connect to xero" in either starter app, i get the following 500 error:

<img width="720" alt="Screenshot 2021-01-07 at 17 26 51" src="https://user-images.githubusercontent.com/12430/103931211-d7b51a80-5117-11eb-93a4-4e2019f48d0c.png">

**Comment by SerKnight** [comment]
responded in https://github.com/XeroAPI/xero-ruby/issues/105
